security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        user_database_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        main:
            lazy: true
            provider: user_database_provider
            custom_authenticator: App\Security\LoginCostumAuthenticator
            # Verwijder form_login omdat custom_authenticator de login afhandelt
           # entry_point: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginCostumAuthenticator
            #pattern: ^/(home)
         #   pattern: ^/
            #pattern: ^/(home|logout)
          #  pattern: ^/(home) 
            form_login:
               login_path: app_login
               check_path: app_login
            logout:
               path: app_logout
               target: app_inlog
                # where to redirect after logout
             
            #    default_target_path: /home
            #    always_use_default_target_path: true
            #    username_parameter: username
            #    password_parameter: password
            #    enable_csrf: true
            #    csrf_parameter: _csrf_token
            #    csrf_token_id: authenticate

            # logout:
            #     path: app_logout
            #     target: app_login 

    access_control:
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/results, roles: ROLE_USER }
      # - { path: ^/inlog, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       ## - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      #  - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, roles: ROLE_USER }

